version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 4200:4200
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
#  mongo:
#   image: mongo:4.2.8
#   ports:
#    - 27017:27017
#   volumes:
#    - mongodb:/data/db
#    - mongodb_config:/data/configdb
# volumes:
#  mongodb:
#  mongodb_config:
